using System.Globalization;
using System.Text;
using TweetCat.Core.Services;

namespace TweetCat.Core.Utilities;

public static class NetscapeCookieWriter
{
    private const string Header = "# Netscape HTTP Cookie File\n" +
                                   "# This file was generated by TweetCat Windows Companion.\n" +
                                   "# Edit at your own risk.\n";

    public static string WriteToString(IEnumerable<BrowserCookie> cookies)
    {
        var builder = new StringBuilder();
        builder.Append(Header);
        foreach (var cookie in cookies)
        {
            var expiration = cookie.Expires.ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture);
            builder.AppendLine(string.Join('\t', new[]
            {
                NormalizeDomain(cookie.Domain),
                cookie.Domain.StartsWith('.') ? "TRUE" : "FALSE",
                cookie.Path,
                cookie.Secure ? "TRUE" : "FALSE",
                expiration,
                cookie.Name,
                cookie.Value
            }));
        }

        return builder.ToString();
    }

    private static string NormalizeDomain(string domain)
    {
        if (string.IsNullOrWhiteSpace(domain))
        {
            return "";
        }

        return domain.StartsWith('.') ? domain : "." + domain;
    }
}
